FROM amazoncorretto:17-alpine-jdk

MAINTAINER emaaristimuno

COPY target/AleBombini-0.0.1-SNAPSHOT.jar AleBombini-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/AleBombini-0.0.1-SNAPSHOT.jar"]

#FROM alpine:latest
#CMD ["/bin/sh"]
